export enum Employee {
  FrankJr = 'FrankJr',
  Gary = 'Gary',
  FrankIII = 'FrankIII',
  John = 'John',
  Lisa = 'Lisa',
  Denise = 'Denise',
  Lindsay = 'Lindsay',
  Matt = 'Matt',
  Jaime = 'Jaime',
  Emily = 'Emily',
  Katie = 'Katie',
  Sarah = 'Sarah',
  Natalee = 'Natalee',
}
